### ISSUE TITLE
Lein test doesn't run, no core namespace

### ISSUE THREAD

**Issue by mobiusinversion** [pallix/lacij#7]
Version 0.9.0, same issue running lein test and also importing into other libraries: 

    Caused by: java.io.FileNotFoundException: Could not locate lacij/core__init.class or lacij/core.clj on classpath:
	at clojure.lang.RT.load(RT.java:443)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__5198.invoke(core.clj:5796)
	at clojure.core$load.doInvoke(core.clj:5795)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5601)
	at clojure.core$load_lib$fn__5147.invoke(core.clj:5641)
	at clojure.core$load_lib.doInvoke(core.clj:5640)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:628)
	at clojure.core$load_libs.doInvoke(core.clj:5679)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:630)
	at clojure.core$use.doInvoke(core.clj:5773)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at lacij.test.core$eval182$loading__5090__auto____183.invoke(core.clj:1)
	at lacij.test.core$eval182.invoke(core.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6757)

**Comment by pallix** [comment]
Fixed in master and deployed on clojars
